CREATE TABLE [dbo].[Events]
(
	[Id] INT CONSTRAINT [PK_Event] PRIMARY KEY IDENTITY(1, 1), 
    [Title] NVARCHAR(128) NOT NULL, 
    [Topic] NVARCHAR(128) NOT NULL, 
    [Description] NVARCHAR(512) NOT NULL, 
    [Schedule] NVARCHAR(512) NOT NULL, 
    [DateTime] SMALLDATETIME NOT NULL, 
    [Place] NVARCHAR(128) NOT NULL
)
